services:
  - type: web
    name: kitchenette
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn kitchenette.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: kitchenette.settings
    migrationsCommand: |
      python manage.py migrate
      python manage.py loaddata menu_data.json
      python manage.py createinitialsuperuser
